# Generated by Django 3.2.2 on 2023-09-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0002_alter_profile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_complaint',
            field=models.CharField(choices=[('water', 'water'), ('road', 'road'), ('electricity', 'electricity'), ('streetlight', 'streetlight'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('ward1', 'ward1'), ('ward2', 'ward2'), ('ward3', 'ward3'), ('ward4', 'ward4'), ('ward5', 'ward5')], default='Ward1', max_length=29),
        ),
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(choices=[('Village1', 'Village1'), ('Village2', 'Village2')], max_length=29),
        ),
    ]
