# Generated by Django 3.2.2 on 2023-09-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0003_auto_20230907_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Branch',
            new_name='Ward',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='collegename',
            new_name='villagename',
        ),
    ]
